# Generated by Django 4.1.2 on 2022-10-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_expired',
            field=models.DateTimeField(null=True, verbose_name='Дата окончания пользования'),
        ),
    ]
