# Generated by Django 4.1.2 on 2022-10-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_usersessions_files_delete_fileset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersessions',
            name='files',
            field=models.FileField(upload_to='session_files'),
        ),
    ]
