# Generated by Django 4.1.2 on 2022-10-09 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaog_id', models.IntegerField()),
                ('file_name_of_session', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('last_message', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='if_service',
            field=models.BooleanField(default=False, verbose_name='Обслуживание пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='usersessions',
            name='files',
            field=models.FileField(upload_to='session_files/%Y_%m_%d_%H_%M'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('message', models.TextField()),
                ('time', models.DateTimeField()),
                ('is_sender', models.BooleanField()),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dialog')),
            ],
        ),
        migrations.AddField(
            model_name='dialog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
