# Generated by Django 4.1.2 on 2022-10-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_dialog_user_if_service_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialog',
            old_name='diaog_id',
            new_name='dialog_id',
        ),
    ]
