# Generated by Django 4.1.2 on 2022-10-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_diaog_id_dialog_dialog_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaded', models.IntegerField()),
                ('not_loaded', models.IntegerField()),
                ('read_dialogs', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_loading_process_started',
            field=models.BooleanField(default=False, verbose_name='Поцесс загрузки запущен'),
        ),
    ]
