# Generated by Django 4.1.2 on 2022-10-10 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_info_user_is_loading_process_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_loading_process_started',
            field=models.BooleanField(default=False, verbose_name='Поцесс загрузки диалогов запущен'),
        ),
    ]
