# Generated by Django 4.1.2 on 2022-10-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_info_loaded_alter_info_not_loaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='all_dialogs',
            field=models.IntegerField(default=0),
        ),
    ]
